import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image: "../../img/1.jpg",
    title: "premium bed",
    author: "Shiv Khera",
    price: "50000",
    categoryName: "bedroom",
    stars: 2,
  },
  {
    _id: uuid(),
    image: "../../img/2.jpg",
    title: "luxurious round table ",
    author: "Junaid Qureshi",
    price: "3000",
    categoryName: "lounge",
    stars: 2.9,
  },
  {
    _id: uuid(),
    image: "../../img/3.jpg",
    title: "boat type table",
    author: "Shiv Khera",
    price: "13500",
    categoryName: "lounge",
    stars: 2.5,
  },
  {
    _id: uuid(),
    image: "../../img/4.jpg",
    title: "king size table",
    author: "Shiv Khera",
    price: "19000",
    categoryName: "dining",
    stars: 4.5,
  },
  {
    _id: uuid(),
    image: "../../img/5.jpg",
    title: "perfect office table",
    author: "Shiv Khera",
    price: "10000",
    categoryName: "office",
    stars: 3.5,
    featured: true,
  },
  {
    _id: uuid(),
    image: "../../img/6.jpg",
    title: "front office desk",
    author: "Shiv Khera",
    price: "15000",
    categoryName: "office",
    stars: 5,
  },
  {
    _id: uuid(),
    image: "../../img/7.jpg",
    title: "vertical desk",
    author: "Shiv Khera",
    price: "1100",
    categoryName: "lounge",
    stars: 4,
  },
  {
    _id: uuid(),
    image: "../../img/8.jpg",
    title: "premium dressing station",
    author: "Shiv Khera",
    price: "10000",
    categoryName: "bedroom",
    stars: 3.4,
  },
  {
    _id: uuid(),
    image: "../../img/9.jpg",
    title: "handcrafted chair",
    author: "Shiv Khera",
    price: "1700",
    categoryName: "bedroom",
    featured: true,
    stars: 4.7,
  },
  {
    _id: uuid(),
    image: "../../img/10.jpg",
    title: "one drawer top",
    author: "Shiv Khera",
    price: "1500",
    categoryName: "bedroom",
    stars: 4.2,
  },
  {
    _id: uuid(),
    image: "../../img/11.jpg",
    title: "king sized dining table",
    author: "Shiv Khera",
    price: "2000",
    categoryName: "dining",
    featured: true,
    stars: 3,
  },
  {
    _id: uuid(),
    image: "../../img/12.jpg",
    title: "wooden made chair",
    author: "Shiv Khera",
    price: "1000",
    categoryName: "office",
    stars: 4.6,
  },
];
